language: node_js
node_js: '0.10'
install: echo "skip install"
branches:
  only: master
env:
  global:
  - secure: gYvLFxy2Mgto6+oeZzny6jgLtNNZ2GeSm9OSABskP0wy86s01WUpuGVWLdyU1DdVdcHRhKK7xl+yFgHBN3tyzz2YgVRNFrJL8jNr0km7H6qLNEghA//ZuDb7w06uW3kOGjtlG4EzheTrG2G6RsmeFflQscaS87t6//b0UTbU3WE=
after_success:
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa
- git remote add deploy $remote
- git push deploy
before_install:
- echo -e "Host scurker.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_6a5cf90fd664_key -iv $encrypted_6a5cf90fd664_iv
  -in deploy-key.enc -out deploy-key -d